server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://documind:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    location /docs {
        proxy_pass http://documind:8000;
    }
    location /openapi.json {
        proxy_pass http://documind:8000;
    }
    location /health {
        proxy_pass http://documind:8000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    client_max_body_size 20M;
}
